// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwkfnr0kBLKanIzYYl7262J1QExLSsZb4',
    appId: '1:384659598515:web:511d1022924bfa801754c6',
    messagingSenderId: '384659598515',
    projectId: 'flutter-5497c',
    authDomain: 'flutter-5497c.firebaseapp.com',
    storageBucket: 'flutter-5497c.firebasestorage.app',
    measurementId: 'G-QKF85YC8ZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5zzhfXpOEnPunoAQ_MUldof0C6J4xEYs',
    appId: '1:384659598515:android:96ea3f92fdd763301754c6',
    messagingSenderId: '384659598515',
    projectId: 'flutter-5497c',
    storageBucket: 'flutter-5497c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBX_srpu1OKz-_rYQOoRjD0ytx_GpZED8',
    appId: '1:384659598515:ios:26608bba2445aeb91754c6',
    messagingSenderId: '384659598515',
    projectId: 'flutter-5497c',
    storageBucket: 'flutter-5497c.firebasestorage.app',
    iosClientId: '384659598515-13t6a0iggoi8jk92io6n4gbr13lsv1fp.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBX_srpu1OKz-_rYQOoRjD0ytx_GpZED8',
    appId: '1:384659598515:ios:26608bba2445aeb91754c6',
    messagingSenderId: '384659598515',
    projectId: 'flutter-5497c',
    storageBucket: 'flutter-5497c.firebasestorage.app',
    iosClientId: '384659598515-13t6a0iggoi8jk92io6n4gbr13lsv1fp.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwkfnr0kBLKanIzYYl7262J1QExLSsZb4',
    appId: '1:384659598515:web:ba9bbf4bc220a9551754c6',
    messagingSenderId: '384659598515',
    projectId: 'flutter-5497c',
    authDomain: 'flutter-5497c.firebaseapp.com',
    storageBucket: 'flutter-5497c.firebasestorage.app',
    measurementId: 'G-RZK5JY0F37',
  );

}